import type { Candidate } from './types';

export const CANDIDATES: Candidate[] = [
  {
    id: 1,
    name: 'Panagiotis Solakidis',
    role: 'Current Role',
    company: 'Company Name',
    experienceYears: '5+ years',
    score: 95,
    scoreBadge: 'Badge',
    city: 'Town',
    country: 'Country',
    apDate: '24/03/2025',
    status: 'New',
    skills: 'Figma, Design Systems, Prototyping, User Research',
    email: 'p.solakidis@email.com',
    phone: '+30 694 123 4567',
  },
  {
    id: 2,
    name: 'Maria Gonzalez',
    role: 'Senior Developer',
    company: 'Tech Innovations Inc.',
    experienceYears: '7 years',
    score: 90,
    scoreBadge: null,
    city: 'Barcelona',
    country: 'Spain',
    apDate: '15/05/2025',
    status: 'Screen Call',
    skills: 'React, TypeScript, Node.js, AWS',
    email: 'm.gonzalez@email.com',
    phone: '+34 612 345 678',
  },
  {
    id: 3,
    name: 'Omar Ali',
    role: 'Product Manager',
    company: 'Creative Solutions LLC',
    experienceYears: '3 years',
    score: 85,
    scoreBadge: 'Past Applicant',
    city: 'Dubai',
    country: 'UAE',
    apDate: '30/04/2025',
    status: 'Assignment',
    skills: 'Product Strategy, Agile, Roadmapping, Stakeholder Management',
    email: 'o.ali@email.com',
    phone: '+971 50 123 4567',
  },
  {
    id: 4,
    name: 'Sofia Ivanov',
    role: 'UX Designer',
    company: 'Design Hub',
    experienceYears: '4 years',
    score: 92,
    scoreBadge: null,
    city: 'Moscow',
    country: 'Russia',
    apDate: '22/06/2025',
    status: 'Ass. Center',
    skills: 'UX Research, Wireframing, Figma, Usability Testing',
    email: 's.ivanov@email.com',
    phone: '+7 916 123 4567',
  },
  {
    id: 5,
    name: 'Liam Johnson',
    role: 'Data Analyst',
    company: 'Data Solutions Co.',
    experienceYears: '6 years',
    score: 88,
    scoreBadge: 'Silver Medalist',
    city: 'Toronto',
    country: 'Canada',
    apDate: '10/08/2025',
    status: 'Ass. Center',
    skills: 'SQL, Python, Tableau, Data Visualization',
    email: 'l.johnson@email.com',
    phone: '+1 416 123 4567',
  },
  {
    id: 6,
    name: 'Aisha Khan',
    role: 'Marketing Specialist',
    company: 'Market Reach Ltd.',
    experienceYears: '2 years',
    score: 80,
    scoreBadge: null,
    city: 'Karachi',
    country: 'Pakistan',
    apDate: '05/09/2025',
    status: 'Ex. Interview',
    skills: 'SEO, Content Strategy, Google Analytics, Social Media',
    email: 'a.khan@email.com',
    phone: '+92 300 123 4567',
  },
  {
    id: 7,
    name: 'James Carter',
    role: 'Frontend Engineer',
    company: 'Webflow Inc.',
    experienceYears: '4 years',
    score: 87,
    scoreBadge: null,
    city: 'London',
    country: 'UK',
    apDate: '12/07/2025',
    status: 'Screen Call',
    skills: 'React, Vue.js, CSS, Performance Optimization',
    email: 'j.carter@email.com',
    phone: '+44 7700 900123',
  },
  {
    id: 8,
    name: 'Yuki Tanaka',
    role: 'Product Designer',
    company: 'Sony Interactive',
    experienceYears: '6 years',
    score: 93,
    scoreBadge: 'Badge',
    city: 'Tokyo',
    country: 'Japan',
    apDate: '01/08/2025',
    status: 'Assignment',
    skills: 'Product Design, Interaction Design, Figma, Accessibility',
    email: 'y.tanaka@email.com',
    phone: '+81 90 1234 5678',
  },
  {
    id: 9,
    name: 'Elena Müller',
    role: 'Data Scientist',
    company: 'SAP SE',
    experienceYears: '5 years',
    score: 91,
    scoreBadge: null,
    city: 'Berlin',
    country: 'Germany',
    apDate: '18/08/2025',
    status: 'New',
    skills: 'Python, Machine Learning, TensorFlow, Data Analysis',
    email: 'e.muller@email.com',
    phone: '+49 176 12345678',
  },
  {
    id: 10,
    name: 'Carlos Romero',
    role: 'Backend Engineer',
    company: 'Mercado Libre',
    experienceYears: '8 years',
    score: 89,
    scoreBadge: 'Silver Medalist',
    city: 'Buenos Aires',
    country: 'Argentina',
    apDate: '25/08/2025',
    status: 'Ass. Center',
    skills: 'Java, PostgreSQL, Microservices, Docker',
    email: 'c.romero@email.com',
    phone: '+54 11 1234 5678',
  },
];

export const TOTAL_CANDIDATES = 48;
